---
- name: Ensure cUrl is installed.
  win_chocolatey:
     name: curl
     state: present
     
- name: Ensure Java is installed
  win_chocolatey:
     name: jre8
     state: present

- name: Ensure Jenkins is installed.
  win_chocolatey:
     name: jenkins
     version: '2.222.4'
     state: present
     params: "/JAVA_HOME:'C:\\program files\\java\\jre1.8.0_421'"
  register: jenkins_install_package_win
